name: my website ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker compose up -d

  # dockerize :
  #   runs-on : self-hosted
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         push: true
  #         tags: brightky/bk-tech:latest
  #     - name: Upload image artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: bk-tech
  #         path: /tmp/bk-tech.tar
  # deploy:
  #   name: deploy-phase
  #   runs-on: self-hosted
  #   needs: dockerize
  #   steps:
  #     - name: Download image artifact
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: bk-tech
  #       path: .
